# Terraform CI Pipeline

name: Build-$(Build.BuildId)

trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - azure-pipelines-dev.yml
pr: none

variables:
- group: DevOps-KV
- group: Terraform

jobs:
- job: infra
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform version $(TF-Version)'
    inputs:
      terraformVersion: $(TF-Version)
  - template: templates/terraform.yml
    parameters:
      saName: $(sa-name)
      blobName: $(blob-name)
      saKey: $(sa-key)
      stateKey: $(key)
      workspace: $(Infra-WS)
      subscriptionId: $(subscription-id)
      clientId: $(client-id)
      clientSecret: $(client-secret)
      tenantId: $(tenant-id)
      repoName: $(repo-name)
      repoUsername: $(repo-username)
      repoPassword: $(repo-password)
- job: dev
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform version $(TF-Version)'
    inputs:
      terraformVersion: $(TF-Version)
  - template: templates/terraform.yml
    parameters:
      saName: $(sa-name)
      blobName: $(blob-name)
      saKey: $(sa-key)
      stateKey: $(key)
      workspace: $(Dev-WS)
      subscriptionId: $(subscription-id)
      clientId: $(client-id)
      clientSecret: $(client-secret)
      tenantId: $(tenant-id)
      repoName: $(repo-name)
      repoUsername: $(repo-username)
      repoPassword: $(repo-password)